[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
extra_output = ["storageLayout"]

[profile.ci]
optimizer = true
optimizer_runs = 1

[fmt]
line_length = 100
sort_imports = true
contract_new_lines = true
bracket_spacing = true
number_underscore = "thousands"
multline_func_header = "all"

[invariant]
runs = 256
depth = 50
fail_on_revert = false
show_solidity = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
